### ISSUE TITLE
闪退加一点建议

### ISSUE THREAD

**Issue by belthil17** [q1263868407/animal-auto#1]
1.82版本，开了一局之后，程序就闪退了，原因未知。
建议加入选人界面自动按空格的功能，目前只能等待60秒的时间来完成选人，加入这个功能会让效率变高很多。

**Comment by belthil17** [comment]
还有一点，如果等级比较低的话，自动升级会导致弹出一些奖励，目前观察下来，脚本遇到弹出奖励的时候，就不会动了

**Comment by AprDeci** [comment]
> 还有一点，如果等级比较低的话，自动升级会导致弹出一些奖励，目前观察下来，脚本遇到弹出奖励的时候，就不会动了

闪退可能有bug，选人界面会自动按空格，检测间隔30s一次，弹出奖励会自动点，检测间隔50s一次。
